[package]
name = "khmer-fst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fst = "0.4.7"
once_cell = "1.19.0"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]
